# fly.toml app configuration file generated for festive-ai-jokes on 2023-12-04T15:33:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "festive-ai-jokes"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
